---

- name: Test Windows Connectivity

  hosts: all

  gather_facts: yes

  

  tasks:

    - name: Basic ping test

      win_ping:


    - name: Get system information

      win_shell: |

        Write-Output "Computer: $env:COMPUTERNAME"

        Write-Output "User: $env:USERNAME"

        Write-Output "Domain: $env:USERDOMAIN"

        Write-Output "OS: $((Get-WmiObject Win32_OperatingSystem).Caption)"

      register: system_info


    - name: Display system information

      debug:

        var: system_info.stdout_lines
