
---

- name: Install VLC Media Player

  hosts: all

  gather_facts: no



  vars:

    vlc_version: "3.0.20"

    temp_dir: "C:\\temp"

    installer_path: "{{ temp_dir }}\\vlc-installer.exe"



  tasks:

    - name: Create temporary directory

      win_file:

        path: "{{ temp_dir }}"

        state: directory



    - name: Check if VLC is already installed

      win_stat:

        path: "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe"

      register: vlc_check



    - name: Skip installation if VLC exists

      debug:

        msg: "VLC is already installed, skipping download and installation"

      when: vlc_check.stat.exists



    - name: Download VLC installer

      win_get_url:

        url: "https://get.videolan.org/vlc/{{ vlc_version }}/win64/vlc-{{ vlc_version }}-win64.exe"

        dest: "{{ installer_path }}"

        timeout: 300

      when: not vlc_check.stat.exists



    - name: Install VLC silently
      win_package:
        path: "{{ installer_path }}"
        arguments: "/S"
        state: present
      when: not vlc_check.stat.exists
      register: install_result

    - name: Verify installation
      win_stat:
        path: "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe"
      register: vlc_installed

    - name: Display installation result
      debug:
        msg: "VLC installation {{ 'successful' if vlc_installed.stat.exists else 'failed' }}"

    - name: Cleanup installer
      win_file:
        path: "{{ installer_path }}"
        state: absent
      when: not vlc_check.stat.exists
