all:

  children:

    windows_servers:

      hosts:

        dc01.lab.local:

          ansible_host: 192.168.10.1

      vars:

        ansible_connection: winrm

        ansible_winrm_transport: ntlm

        ansible_winrm_scheme: http

        ansible_winrm_server_cert_validation: ignore

        ansible_port: 5985

        ansible_winrm_domain: lab



    linux_servers:

      hosts:

        uflin01.lab.local:

          ansible_host: 192.168.10.32

        aiopsawx01.lab.local:

          ansible_host: 192.168.10.11

      vars:

        ansible_connection: ssh


