all:
  children:
    windows_servers:
      hosts:
        dc01.lab.local:
          ansible_host: 192.168.10.1
        testwin01.lab.local:
          ansible_host: 192.168.10.21
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_port: 5985
